# Generated by Django 4.2 on 2023-05-15 22:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('desc', models.TextField(null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('front_word', models.CharField(blank=True, max_length=255)),
                ('front_pic', models.FileField(blank=True, upload_to='cards/pictures')),
                ('back', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.attempt')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.originalcard')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_wrong', models.DateField(default=datetime.date(2023, 5, 16))),
                ('next_review', models.DateField(default=datetime.date(2023, 5, 16))),
                ('original_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.originalcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.userprofile'),
        ),
    ]
