# Generated by Django 4.2 on 2023-05-18 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_wrong',
            field=models.DateField(default=datetime.date(2023, 5, 18)),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateField(default=datetime.date(2023, 5, 18)),
        ),
    ]
