# Generated by Django 4.2 on 2023-05-20 16:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_alter_originalcard_front_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_wrong',
            field=models.DateField(default=datetime.date(2023, 5, 20)),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateField(default=datetime.date(2023, 5, 20)),
        ),
        migrations.CreateModel(
            name='DeckPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
