# Generated by Django 4.2 on 2023-05-23 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_last_wrong_alter_card_next_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_wrong',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
    ]
