# Generated by Django 4.2 on 2023-05-29 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_last_wrong_alter_card_next_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='card',
        ),
        migrations.AlterField(
            model_name='card',
            name='last_wrong',
            field=models.DateField(default=datetime.date(2023, 5, 29)),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateField(default=datetime.date(2023, 5, 29)),
        ),
        migrations.AlterField(
            model_name='cardsuserprofile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher')], default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
