# Generated by Django 4.2 on 2023-05-30 01:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_attempt_mark_delete_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='mark',
        ),
        migrations.AlterField(
            model_name='card',
            name='last_wrong',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.attempt')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.originalcard')),
            ],
        ),
    ]
