# Generated by Django 4.2 on 2023-05-15 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FileField(default='audio/default_start.mp3', upload_to='audio/')),
                ('start_speaking', models.FileField(default='audio/default_speak.mp3', upload_to='audio/')),
                ('end', models.FileField(default='audio/default_end.mp3', upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('audio', models.FileField(upload_to='%Y/%m/%d/audio/text/')),
                ('text', models.TextField()),
                ('prepare_time', models.IntegerField(default=90)),
                ('record_time', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('audio', models.FileField(upload_to='%Y/%m/%d/audio/ad/')),
                ('pic_caption', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='%Y/%m/%d/photos/ad/')),
                ('question1', models.FileField(upload_to='%Y/%m/%d/audio/ad/')),
                ('question2', models.FileField(upload_to='%Y/%m/%d/audio/ad/')),
                ('question3', models.FileField(upload_to='%Y/%m/%d/audio/ad/')),
                ('question4', models.FileField(upload_to='%Y/%m/%d/audio/ad/')),
                ('prepare_time', models.IntegerField(default=90)),
                ('record_time', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('audio', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('start_audio', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('question1', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('question2', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('question3', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('question4', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('question5', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('question6', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('end_audio', models.FileField(upload_to='%Y/%m/%d/audio/interview/')),
                ('prepare_time', models.IntegerField(default=20)),
                ('timer', models.IntegerField(default=5)),
                ('record_time', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Task4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('audio', models.FileField(upload_to='%Y/%m/%d/audio/pic_desc/')),
                ('pic1', models.ImageField(upload_to='%Y/%m/%d/photos/pic_desc/')),
                ('pic2', models.ImageField(upload_to='%Y/%m/%d/photos/pic_desc/')),
                ('pic3', models.ImageField(upload_to='%Y/%m/%d/photos/pic_desc/')),
                ('prepare_time', models.IntegerField(default=150)),
                ('record_time', models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='VPRVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task1', verbose_name='Text Task')),
                ('task2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task4', verbose_name='Pic Desc Task')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OGEVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task1', verbose_name='Text Task')),
                ('task2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task3', verbose_name='Interview Task')),
                ('task3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task4', verbose_name='Talk Task')),
            ],
        ),
        migrations.CreateModel(
            name='EGEVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task1', verbose_name='Text Task')),
                ('task2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task2', verbose_name='Ad Task')),
                ('task3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task3', verbose_name='Interview Task')),
                ('task4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.task4', verbose_name='Pic Desc Task')),
            ],
        ),
    ]
