# Generated by Django 4.2 on 2023-05-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_egepopularity_ogepopularity_vprpopularity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egepopularity',
            old_name='ege_variant',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='ogepopularity',
            old_name='oge_variant',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='vprpopularity',
            old_name='vpr_variant',
            new_name='variant',
        ),
    ]
