# Generated by Django 4.2 on 2023-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='egevariant',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ogevariant',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vprvariant',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
