# Generated by Django 4.2 on 2023-05-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_egevariant_pdf_ogevariant_pdf_vprvariant_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egevariant',
            name='pdf',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/pdf/'),
        ),
        migrations.AlterField(
            model_name='ogevariant',
            name='pdf',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/pdf/'),
        ),
        migrations.AlterField(
            model_name='task3',
            name='question6',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/audio/interview/'),
        ),
        migrations.AlterField(
            model_name='task4',
            name='pic3',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/photos/pic_desc/'),
        ),
        migrations.AlterField(
            model_name='vprvariant',
            name='pdf',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/pdf/'),
        ),
    ]
